Telecom X - An√°lise de Evas√£o de Clientes

Voc√™ foi contratado como assistente de an√°lise de dados na Telecom X e far√° parte do projeto "Churn de Clientes". A empresa enfrenta um alto √≠ndice de cancelamentos e precisa entender os fatores que levam √† perda de clientes.

Seu desafio ser√° coletar, tratar e analisar os dados, utilizando Python e suas principais bibliotecas para extrair insights valiosos. A partir da sua an√°lise, os demais colegas da equipe de Data Science poder√° avan√ßar para modelos preditivos e desenvolver estrat√©gias para reduzir a evas√£o.

O que voc√™ vai praticar:

‚úÖ Importar e manipular dados de uma API de forma eficiente. ‚úÖ Aplicar os conceitos de ETL (Extra√ß√£o, Transforma√ß√£o e Carga) na prepara√ß√£o dos dados. ‚úÖ Criar visualiza√ß√µes de dados estrat√©gicas para identificar padr√µes e tend√™ncias. ‚úÖ Realizar uma An√°lise Explorat√≥ria de Dados (EDA) e gerar um relat√≥rio com insights relevantes.

Agora √© sua vez! üöÄ Use seus conhecimentos para transformar dados brutos em informa√ß√µes estrat√©gicas e ajudar a Telecom X a reter mais clientes.

#üìå Extra√ß√£o

‚úÖ Carregar os dados diretamente da API utilizando Python.
‚úÖ Converter os dados para um DataFrame do Pandas para facilitar a manipula√ß√£o.

In [ ]:
# importa√ß√£o de bibliotecas
# pandas
import pandas as pd
from pandas import json_normalize

# numpy
import numpy as np

### Executa somente no primeiro tratamento do dataframe

In [ ]:
#### ATEN√á√ÉO ####

# Leitura do arquivo no formato JSON e o converte em um DataFrame do pandas.
dados_telecom = pd.read_json('/content/TelecomX_Data.json')

# Exibe as primeiras linhas do DataFrame (por padr√£o, as 5 primeiras).
dados_telecom.head()

,id.cliente,contrato.ativo,cliente.genero,cliente.idoso,cliente.casado,cliente.dependentes,cliente.tempo.contrato,fone.assinatura,fone.assinatura.adicional,internet.assinatura,...,internet.protecao.dispositivo,internet.suporte,internet.streaming.tv,internet.streamingtv.filmes,conta.tipo.contrato,conta.fatura.digital,conta.metodo.pagamento,conta.valor.mensal,conta.valor.total.acumulado,conta.valor.diario
0,0002-ORFBO,0,female,0,1,1,9,1,0,dsl,...,0,1,1,0,one year,1,mailed check,65.6,593.30,2.155059
1,0003-MKNFE,0,male,0,0,0,9,1,1,dsl,...,0,0,0,1,month-to-month,0,mailed check,59.9,542.40,1.967806
2,0004-TLHLJ,1,male,0,0,0,4,1,0,fiber optic,...,1,0,0,0,month-to-month,1,electronic check,73.9,280.85,2.427727
3,0011-IGKFF,1,male,1,1,0,13,1,0,fiber optic,...,1,0,1,1,month-to-month,1,electronic check,98.0,1237.85,3.219448
4,0013-EXCHZ,1,female,1,1,0,3,1,0,fiber optic,...,0,1,1,0,month-to-month,1,mailed check,83.9,267.40,2.756242

### Executa somente nos processos de an√°lise e manuten√ß√£o

In [ ]:
#  Leitura do arquivo no formato JSON e o converte em um DataFrame do pandas.
df_normalizado = pd.read_json('/content/TelecomX_normalizado.json2', lines=True)
df_normalizado.head()

,id.cliente,contrato.ativo,cliente.genero,cliente.idoso,cliente.casado,cliente.dependentes,cliente.tempo.contrato,fone.assinatura,fone.assinatura.adicional,internet.assinatura,...,internet.protecao.dispositivo,internet.suporte,internet.streaming.tv,internet.streamingtv.filmes,conta.tipo.contrato,conta.fatura.digital,conta.metodo.pagamento,conta.valor.mensal,conta.valor.total.acumulado,conta.valor.diario
0,0002-ORFBO,0,female,0,1,1,9,1,0,dsl,...,0,1,1,0,one year,1,mailed check,65.6,593.30,2.155059
1,0003-MKNFE,0,male,0,0,0,9,1,1,dsl,...,0,0,0,1,month-to-month,0,mailed check,59.9,542.40,1.967806
2,0004-TLHLJ,1,male,0,0,0,4,1,0,fiber optic,...,1,0,0,0,month-to-month,1,electronic check,73.9,280.85,2.427727
3,0011-IGKFF,1,male,1,1,0,13,1,0,fiber optic,...,1,0,1,1,month-to-month,1,electronic check,98.0,1237.85,3.219448
4,0013-EXCHZ,1,female,1,1,0,3,1,0,fiber optic,...,0,1,1,0,month-to-month,1,mailed check,83.9,267.40,2.756242

#### Dicion√°rio de dados

* `customerID`: n√∫mero de identifica√ß√£o √∫nico de cada cliente
* `Churn`: se o cliente deixou ou n√£o a empresa
* `gender`: g√™nero (masculino e feminino)
* `SeniorCitizen`: informa√ß√£o sobre um cliente ter ou n√£o idade igual ou maior que 65 anos
* `Partner`:  se o cliente possui ou n√£o um parceiro ou parceira
* `Dependents`: se o cliente possui ou n√£o dependentes
* `tenure`:  meses de contrato do cliente
* `PhoneService`: assinatura de servi√ßo telef√¥nico
* `MultipleLines`: assinatura de mais de uma linha de telefone
* `InternetService`: assinatura de um provedor internet
* `OnlineSecurity`: assinatura adicional de seguran√ßa online
* `OnlineBackup`: assinatura adicional de backup online
* `DeviceProtection`: assinatura adicional de prote√ß√£o no dispositivo
* `TechSupport`: assinatura adicional de suporte t√©cnico, menos tempo de espera
* `StreamingTV`: assinatura de TV a cabo
* `StreamingMovies`: assinatura de streaming de filmes
* `Contract`: tipo de contrato
* `PaperlessBilling`: se o cliente prefere receber online a fatura
* `PaymentMethod`: forma de pagamento
* `Charges.Monthly`: total de todos os servi√ßos do cliente por m√™s
* `Charges.Total`: total gasto pelo cliente

#üîß Transforma√ß√£o

### Processo inicial de normaliza√ß√£o dos dados. Executar apenas no primeiro processo

In [ ]:
# Usando json_normalize para "achatar" os dicion√°rios aninhados
df_normalizado = pd.json_normalize( dados_telecom.to_dict(orient='records') )

# Visualizar dos dados
df_normalizado

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

In [ ]:
# apresenta informa√ß√£o das colunas dispon√≠veis
df_normalizado.dtypes

customerID                    object
Churn                         object
customer.gender               object
customer.SeniorCitizen         int64
customer.Partner              object
customer.Dependents           object
customer.tenure                int64
phone.PhoneService            object
phone.MultipleLines           object
internet.InternetService      object
internet.OnlineSecurity       object
internet.OnlineBackup         object
internet.DeviceProtection     object
internet.TechSupport          object
internet.StreamingTV          object
internet.StreamingMovies      object
account.Contract              object
account.PaperlessBilling      object
account.PaymentMethod         object
account.Charges.Monthly      float64
account.Charges.Total         object
dtype: object

## Verifica valores nulos e duplicados

In [ ]:
# verifica se existem valores nulos
df_normalizado.isnull().sum()

customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

In [ ]:
# verifica se existem valores duplicados
df_normalizado.duplicated().sum()

np.int64(0)

## Converte colunas Object para float

In [ ]:
# converte cooluna total para float
df_normalizado['account.Charges.Total'] = pd.to_numeric(df_normalizado['account.Charges.Total'], errors='coerce')

In [ ]:
# converte valores NaN = 0
df_normalizado['account.Charges.Total'] = df_normalizado['account.Charges.Total'].fillna(0)

In [ ]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

## Trata colunas Object - converte colunas de texto em min√∫sculas e remove espa√ßos

In [ ]:
# converte em min√∫sculas e remove espa√ßos, exceto CUSTOMERID
df_normalizado = df_normalizado.apply(
    lambda col: col.str.strip().str.lower() if col.name not in ['customerID'] and col.dtypes == 'object' else col
)

In [ ]:
# verifica se existem valores nulos
df_normalizado['Churn'].isna().sum()

np.int64(0)

In [ ]:
# Verificar todos os valores √∫nicos da coluna - Isso mostra todos os valores distintos presentes, incluindo erros como 'yes', ' NO', 'Sim', '0', etc
for col in df_normalizado.select_dtypes(include='object').columns:
    print(f"\nColuna: {col}")
    print(df_normalizado[col].unique())

Coluna: customerID
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']

Coluna: Churn
['no' 'yes' '']

Coluna: customer.gender
['female' 'male']

Coluna: customer.Partner
['yes' 'no']

Coluna: customer.Dependents
['yes' 'no']

Coluna: phone.PhoneService
['yes' 'no']

Coluna: phone.MultipleLines
['no' 'yes' 'no phone service']

Coluna: internet.InternetService
['dsl' 'fiber optic' 'no']

Coluna: internet.OnlineSecurity
['no' 'yes' 'no internet service']

Coluna: internet.OnlineBackup
['yes' 'no' 'no internet service']

Coluna: internet.DeviceProtection
['no' 'yes' 'no internet service']

Coluna: internet.TechSupport
['yes' 'no' 'no internet service']

Coluna: internet.StreamingTV
['yes' 'no' 'no internet service']

Coluna: internet.StreamingMovies
['no' 'yes' 'no internet service']

Coluna: account.Contract
['one year' 'month-to-month' 'two year']

Coluna: account.PaperlessBilling
['yes' 'no']

Coluna: account.PaymentMethod
['mailed check' 'electronic check' 'credit card (automatic)'
 'bank transfer (automatic)']

## Tratamento dos valores para um modelo preditivo

### Remove registros inconsistentes da coluna CHURN

In [ ]:
# Removendo registros com Churn = ''
# O alvo (Churn) √© a vari√°vel que o modelo tenta prever.
# Registros com valor vazio n√£o ajudam o modelo ‚Äî n√£o t√™m r√≥tulo para aprender.
# Podem introduzir ru√≠do e confundir o algoritmo, prejudicando a performance.

# Verifica quantos registros devem ser removidos:
print("Antes:", df_normalizado.shape[0])

# verifica quantos registros da coluna CHURN tem valor = ''
filtro_vazios = df_normalizado[df_normalizado['Churn'] == '']
print("Total de registros com Churn vazio:", filtro_vazios.shape[0])

# remove registros com CHURN = ''
df_normalizado = df_normalizado[df_normalizado['Churn'].isin(['yes', 'no'])]

# Verifica quantos registros devem ser removidos:
print("Depois:", df_normalizado.shape[0])

Antes: 7267
Total de registros com Churn vazio: 224
Depois: 7043

In [ ]:
df_normalizado['Churn'].unique()

array(['no', 'yes'], dtype=object)

### Padroniza√ß√£o da colunaphone.MultipleLines

In [ ]:
# Conte√∫do encontrado = ['no' 'yes' 'no phone service']
print(df_normalizado['phone.MultipleLines'].unique())
df_normalizado['phone.MultipleLines'] = df_normalizado['phone.MultipleLines'].replace('no phone service', 'no')
print(df_normalizado['phone.MultipleLines'].unique())

['no' 'yes' 'no phone service']
['no' 'yes']

### Valida√ß√£o de inconsist√™ncia das informa√ß√µes de contrata√ß√£o de internet e streaming

Padronizando 'no internet service' para valor booleano 'no'

Na maioria dos casos de modelagem preditiva, substituir 'no internet service' por 'no' √© uma escolha apropriada e eficaz.

As colunas como OnlineSecurity, OnlineBackup, TechSupport, etc. dependem da presen√ßa de servi√ßo de internet. Quando o cliente n√£o tem internet, esses servi√ßos naturalmente n√£o est√£o dispon√≠veis, o que na pr√°tica √© equivalente a 'no'.

‚úÖ Portanto:

Valor original = [1- 'no internet service']	[2- 'no']

Interpreta√ß√£o pr√°tica	= [1- N√£o usa o servi√ßo] [2- Usa, mas desabilitado]

Valor convertido = 'no'


‚úÖ Vantagens da convers√£o:

Reduz o n√∫mero de categorias ‚Üí melhora o desempenho e evita overfitting.

Simplifica a codifica√ß√£o.

Evita dados esparsos ao usar One-Hot Encoding.

Para modelagem preditiva, especialmente churn, isso raramente ajuda e s√≥ aumenta a complexidade sem ganhos.

Antes, por√©m, √© coerente e importante validar isso antes da substitui√ß√£o, e sua linha de racioc√≠nio est√° alinhada com uma an√°lise de dados respons√°vel.

‚úÖ Por que essa verifica√ß√£o √© necess√°ria?
Porque:

* Se um cliente tem internet.InternetService = 'dsl' ou 'fiber optic' (ou seja, tem internet),
* Mas aparece como 'no internet service' em colunas como OnlineSecurity, isso indica inconsist√™ncia nos dados (erro de entrada, registro inv√°lido etc.).

In [ ]:
# Verificar inconsist√™ncias
inconsistentes = df_normalizado[
    (df_normalizado['internet.InternetService'].isin(['dsl', 'fiber optic'])) &
    (
        (df_normalizado['internet.OnlineSecurity'] == 'no internet service') |
        (df_normalizado['internet.OnlineBackup'] == 'no internet service') |
        (df_normalizado['internet.DeviceProtection'] == 'no internet service') |
        (df_normalizado['internet.TechSupport'] == 'no internet service') |
        (df_normalizado['internet.StreamingTV'] == 'no internet service') |
        (df_normalizado['internet.StreamingMovies'] == 'no internet service')
    )
]

print(f"Registros inconsistentes encontrados: {inconsistentes.shape[0]}")

Registros inconsistentes encontrados: 0

In [ ]:
# Converte conte√∫do dos registros = 'no internet service' para 'no'
colunas_internet = [
    'internet.OnlineSecurity',
    'internet.OnlineBackup',
    'internet.DeviceProtection',
    'internet.TechSupport',
    'internet.StreamingTV',
    'internet.StreamingMovies'
]

for col in colunas_internet:
    df_normalizado[col] = df_normalizado[col].replace('no internet service', 'no')
    print(f"{col}: {df_normalizado[col].unique()}")

internet.OnlineSecurity: ['no' 'yes']
internet.OnlineBackup: ['yes' 'no']
internet.DeviceProtection: ['no' 'yes']
internet.TechSupport: ['yes' 'no']
internet.StreamingTV: ['yes' 'no']
internet.StreamingMovies: ['no' 'yes']

### Converte valores 'yes' e 'no' do tipo object em tipo num√©rico

In [ ]:
# salva uma c√≥pia do dataframe para backup de seguran√ßa
df_normalizado.to_json('backup_dados.json2', orient='records', lines=True, force_ascii=False)

In [ ]:
# converte os valores OBJECT 'yes' e 'no' em num√©rico 1 e 0, para modelo preditivo
for col in df_normalizado.select_dtypes(include='object').columns:
    valores_unicos = df_normalizado[col].dropna().str.strip().str.lower().unique()
    if set(valores_unicos).issubset({'yes', 'no'}):
        print(f"Convertendo coluna: {col}")
        df_normalizado[col] = df_normalizado[col].str.strip().str.lower().map({'yes': 1, 'no': 0})

Convertendo coluna: Churn
Convertendo coluna: customer.Partner
Convertendo coluna: customer.Dependents
Convertendo coluna: phone.PhoneService
Convertendo coluna: phone.MultipleLines
Convertendo coluna: internet.OnlineSecurity
Convertendo coluna: internet.OnlineBackup
Convertendo coluna: internet.DeviceProtection
Convertendo coluna: internet.TechSupport
Convertendo coluna: internet.StreamingTV
Convertendo coluna: internet.StreamingMovies
Convertendo coluna: account.PaperlessBilling

In [ ]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   int64
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   int64
 5   customer.Dependents        7043 non-null   int64
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   int64
 8   phone.MultipleLines        7043 non-null   int64
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   int64
 11  internet.OnlineBackup      7043 non-null   int64
 12  internet.DeviceProtection  7043 non-null   int64
 13  internet.TechSupport       7043 non-null   int64
 14  internet.StreamingTV       7043 non-null   int64
 15  internet.StreamingMovies   7043 non-null   int64
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   int64
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7043 non-null   float64
dtypes: float64(2), int64(14), object(5)
memory usage: 1.4+ MB

In [ ]:
# valida√ß√£o dos dados padronizados
for col in df_normalizado.columns:
    print(f"\nColuna: {col}")
    print(df_normalizado[col].unique())

Coluna: customerID
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']

Coluna: Churn
[0 1]

Coluna: customer.gender
['female' 'male']

Coluna: customer.SeniorCitizen
[0 1]

Coluna: customer.Partner
[1 0]

Coluna: customer.Dependents
[1 0]

Coluna: customer.tenure
[ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 37 49 66 67
 20 43 59 12 27  2 25 29 14 35 64 39 40 11  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 31 36 17 18 51 38 42
  0]

Coluna: phone.PhoneService
[1 0]

Coluna: phone.MultipleLines
[0 1]

Coluna: internet.InternetService
['dsl' 'fiber optic' 'no']

Coluna: internet.OnlineSecurity
[0 1]

Coluna: internet.OnlineBackup
[1 0]

Coluna: internet.DeviceProtection
[0 1]

Coluna: internet.TechSupport
[1 0]

Coluna: internet.StreamingTV
[1 0]

Coluna: internet.StreamingMovies
[0 1]

Coluna: account.Contract
['one year' 'month-to-month' 'two year']

Coluna: account.PaperlessBilling
[1 0]

Coluna: account.PaymentMethod
['mailed check' 'electronic check' 'credit card (automatic)'
 'bank transfer (automatic)']

Coluna: account.Charges.Monthly
[65.6  59.9  73.9  ... 91.75 68.8  67.85]

Coluna: account.Charges.Total
[ 593.3   542.4   280.85 ...  742.9  4627.65 3707.6 ]

### Renomeando colunas

In [ ]:
df_normalizado.rename(columns={
    'customerID': 'id.cliente',
    'Churn': 'contrato.ativo',
    'customer.gender': 'cliente.genero',
    'customer.SeniorCitizen': 'cliente.idoso',
    'customer.Partner': 'cliente.casado',
    'customer.Dependents': 'cliente.dependentes',
    'customer.tenure': 'cliente.tempo.contrato',

    'phone.PhoneService': 'fone.assinatura',
    'phone.MultipleLines': 'fone.assinatura.adicional',

    'internet.InternetService': 'internet.assinatura',
    'internet.OnlineSecurity': 'internet.seguranca',
    'internet.OnlineBackup': 'internet.backup',
    'internet.DeviceProtection': 'internet.protecao.dispositivo',
    'internet.TechSupport': 'internet.suporte',
    'internet.StreamingTV': 'internet.streaming.tv',
    'internet.StreamingMovies': 'internet.streamingtv.filmes',

    'account.Contract': 'conta.tipo.contrato',
    'account.PaperlessBilling': 'conta.fatura.digital',
    'account.PaymentMethod': 'conta.metodo.pagamento',
    'account.Charges.Monthly': 'conta.valor.mensal',
    'account.Charges.Total': 'conta.valor.total.acumulado'
}, inplace=True)

In [ ]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id.cliente                     7043 non-null   object
 1   contrato.ativo                 7043 non-null   int64
 2   cliente.genero                 7043 non-null   object
 3   cliente.idoso                  7043 non-null   int64
 4   cliente.casado                 7043 non-null   int64
 5   cliente.dependentes            7043 non-null   int64
 6   cliente.tempo.contrato         7043 non-null   int64
 7   fone.assinatura                7043 non-null   int64
 8   fone.assinatura.adicional      7043 non-null   int64
 9   internet.assinatura            7043 non-null   object
 10  internet.seguranca             7043 non-null   int64
 11  internet.backup                7043 non-null   int64
 12  internet.protecao.dispositivo  7043 non-null   int64
 13  internet.suporte               7043 non-null   int64
 14  internet.streaming.tv          7043 non-null   int64
 15  internet.streamingtv.filmes    7043 non-null   int64
 16  conta.tipo.contrato            7043 non-null   object
 17  conta.fatura.digital           7043 non-null   int64
 18  conta.metodo.pagamento         7043 non-null   object
 19  conta.valor.mensal             7043 non-null   float64
 20  conta.valor.total.acumulado    7043 non-null   float64
dtypes: float64(2), int64(14), object(5)
memory usage: 1.4+ MB

### Criando uma coluna de Contas_Diarias

Agora, com os dados limpos, vamos criar a coluna "Contas_Diarias". Utilizando o faturamento mensal para calcular o valor di√°rio, proporcionando uma vis√£o mais detalhada do comportamento dos clientes ao longo do tempo.

In [ ]:
# C√°lculo do valor di√°rio, com base no valor mensal.
# Para um valor mais preciso, usamos como base no n√∫mero exato de dias (como 30.44, que √© a m√©dia do ano)

df_normalizado['conta.valor.diario'] = df_normalizado['conta.valor.mensal'] / 30.44

In [ ]:
print(df_normalizado[['conta.valor.mensal', 'conta.valor.diario']].head())

   conta.valor.mensal  conta.valor.diario
0                65.6            2.155059
1                59.9            1.967806
2                73.9            2.427727
3                98.0            3.219448
4                83.9            2.756242

## Exporta dataframe tratado

In [ ]:
# salva uma c√≥pia do dataframe normalizado
df_normalizado.to_json('TelecomX_normalizado.json2', orient='records', lines=True, force_ascii=False)